export const ActionTypes = {
    SET_PRODUCTS            : "SET_PRODUCTS",
    SELECTED_PRODUCT        : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_PRODUCT             : "ADD_PRODUCT",

    SET_TYPES               : "SET_TYPES",
    SELECTED_TYPE           : "SELECTED_TYPE",
    REMOVE_SELECTED_TYPE    : "REMOVE_SELECTED_TYPE",

    SET_SUB_TYPES           : "SET_SUB_TYPES",
    SELECTED_SUB_TYPE       : "SELECTED_SUB_TYPE",
    REMOVE_SELECTED_SUB_TYPE: "REMOVE_SELECTED_SUB_TYPE",

    SET_IMAGES              : "SET_IMAGES",
    ADD_IMAGE               : "ADD_IMAGE",
    REMOVE_SELECTED_IMAGE   : "REMOVE_SELECTED_IMAGE",
};