export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    SET_TYPES: "SET_TYPES",
    SELECTED_TYPE: "SELECTED_TYPE",
    REMOVE_SELECTED_TYPE: "REMOVE_SELECTED_TYPE",
};